// ─────────────────────────────────────────────
//  PLUG QUESTS (DOM-90)
//  One-shot, data-driven (data/quests.json — generated by gen-catalog.js).
//  Steps route through the NORMAL faucets: the jobs and fights a quest asks
//  for pay their usual rates while you grind them, so the 60:35 Clout mix is
//  untouched; the completion bonus is the only new money, priced by rule
//  (hours of best-job income at the quest's gate). Ratified 2026-09-14.
// ─────────────────────────────────────────────

// One quest per Plug in v1 — the card and the dialog panel both key off this.
function questFor(plugId) {
  return (typeof QUESTS !== 'undefined' && QUESTS)
    ? QUESTS.find(q => q.plug === plugId) || null : null;
}

// Progress lives at G.quests[questId] = { p: [count per step], claimed }.
// Item steps are never counted — ownership is checked live, so selling/losing
// mechanics added later cannot strand a stale tick.
function _questCounters(q) {
  G.quests = G.quests || {};
  if (!G.quests[q.id]) G.quests[q.id] = { p: q.steps.map(() => 0), claimed: false };
  const st = G.quests[q.id];
  if (!Array.isArray(st.p) || st.p.length !== q.steps.length) {
    st.p = q.steps.map((_, i) => (Array.isArray(st.p) && st.p[i]) || 0);
  }
  return st;
}

function questUnlocked(q) { return G.level >= (q.levelReq || 1); }
function questClaimed(q) {
  const st = (G.quests || {})[q.id];
  return !!(st && st.claimed);
}
function questStepTarget(s) { return s.type === 'item' ? 1 : s.count; }
function questStepProgress(q, i) {
  const s = q.steps[i];
  if (s.type === 'item') return ownsGear(s.id) ? 1 : 0;
  return Math.min(_questCounters(q).p[i], s.count);
}
function questComplete(q) {
  return q.steps.every((s, i) => questStepProgress(q, i) >= questStepTarget(s));
}
// Whole-quest progress as done/total ticks, for the card chip.
function questProgress(q) {
  return {
    done: q.steps.reduce((s, _, i) => s + questStepProgress(q, i), 0),
    total: q.steps.reduce((s, step) => s + questStepTarget(step), 0),
  };
}

// Counter hooks, called by doJob and the fight resolution. Counting stops at
// the step target so a save never carries unbounded numbers, and nothing
// counts before the quest's level gate — grinding ahead is not banked.
const Quests = {
  onJob(jobId) { this._bump('job', jobId); },
  onFightWin(enemyId) { this._bump('fight', enemyId); },
  _bump(type, id) {
    if (typeof QUESTS === 'undefined' || !QUESTS) return;
    for (const q of QUESTS) {
      if (!questUnlocked(q) || questClaimed(q)) continue;
      q.steps.forEach((s, i) => {
        if (s.type !== type || s.id !== id) return;
        const st = _questCounters(q);
        if (st.p[i] < s.count) st.p[i]++;
      });
    }
  },
};

function claimQuest(qid) {
  const q = QUESTS.find(x => x.id === qid);
  if (!q) return;
  if (!questUnlocked(q)) { toast('Level ' + q.levelReq + ' first.', true); return; }
  if (questClaimed(q)) { toast('Already collected.', true); return; }
  if (!questComplete(q)) { toast("Work's not done yet.", true); return; }

  _questCounters(q).claimed = true;   // marked before payout: a throw mid-grant must not allow a re-claim
  credit('cash', q.reward.cash, REASON.QUEST_REWARD, { ref: { questId: q.id } });
  addClout(q.reward.clout, REASON.QUEST_REWARD, { questId: q.id });
  let itemNote = '';
  if (q.reward.item && !ownsGear(q.reward.item)) {
    grantGear(q.reward.item, 'quest');
    autoFieldGear(q.reward.item);
    const item = STORE_ITEMS.find(i => i.id === q.reward.item);
    itemNote = item ? ' + ' + item.name : '';
  }
  log('QUEST — ' + q.name + ': +$' + q.reward.cash.toLocaleString()
    + ' + ' + q.reward.clout + ' Clout' + itemNote, 'win');
  toast('+$' + q.reward.cash.toLocaleString() + ' | +' + q.reward.clout + ' CLOUT' + itemNote);
  if (typeof Sound !== 'undefined' && Sound.win) Sound.win();
  updateHUD();
  if (typeof renderPlugs === 'function') renderPlugs();
  const overlay = $('plug-overlay');
  if (overlay && overlay.classList.contains('open') && typeof _renderPlugDialog === 'function') {
    _renderPlugDialog(parseInt(overlay.dataset.idx, 10));
  }
  GameState.save();
}
